import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/for-developers',
        'getting-started/for-pm-ba',
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      collapsed: false,
      items: [
        'workflow/overview',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'commands'}],
    },
    {
      type: 'category',
      label: 'GitHub Actions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'github-actions'}],
    },
  ],
};

export default sidebars;
